# Generated by Django 6.0 on 2026-01-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pets',
            new_name='Pet',
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Zwierzę', 'verbose_name_plural': 'Zwierzęta'},
        ),
    ]
