# Generated by Django 6.0 on 2026-01-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctor_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('planned', 'Zaplanowana'), ('completed', 'Zakończona'), ('cancelled', 'Anulowana')], default='planned', max_length=20),
        ),
    ]
