# Generated by Django 6.0 on 2026-01-04 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('phone', models.CharField(help_text='Numer kontaktowy', max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name'], 'verbose_name': 'Zwierzę', 'verbose_name_plural': 'Zwierzęta'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner_phone',
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Rasa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(help_text='np. pies, kot', max_length=100, verbose_name='Gatunek'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.client', verbose_name='Właściciel'),
        ),
    ]
